# Generated by Django 4.2.6 on 2023-10-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_people_person_alter_bookcopy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='core.bookcopy', verbose_name='Book Copy'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseves', to='core.bookcopy', verbose_name='Book Copy'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
